### PR TITLE
add a Grunt plugin

### PR DESCRIPTION
**Pull request by danbev**

### CODE REVIEW

**Comment by lholmquist** [comment]
@danbev i'm not opposed to adding this, But i was just thinking about if it should go in the main project, or should be a separate project, like szero-grunt(or something like that) that has szero as a dependecy.  

The only reason i'm thinking this, is if we wanted a gulp plugin, or broccoli plugin, or brand new thing plugin.

If there are methods that the plugin needs that aren't public, we can make it happen.

Thoughts? @danbev @helio-frota @lance

**Comment by danbev** [comment]
@lholmquist I'm cool either way. Just wanted to use this this with the sync server stuff and Grunt is what we are using there.

**Comment by helio-frota** [comment]
@lholmquist :+1: for szero-grunt

**Comment by lholmquist** [comment]
closing since it probably makes more sense for the split discussed above

**Pull request closed without merging**
